name: "Create Release"

on:
    - workflow_dispatch

jobs:
    create_release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: Proyecto2025-0.0.5
                  body_path: ./release_notes.md
                  token: ${{ secrets.RELEASE_TOKEN }}
