name: Deployment

on:
    push:
        branches:
        - main
        - dev

env:
    MONGODB_DB_NAME: mp_ghademo

jobs:
    test: 
        env: 
            MONGODB_CLUSTER_ADDRESS: cluster0.phy2t.mongodb.net
            MONGODB_USERNAME: mpoveda
            MONGODB_PASSWORD: sts15ue2uAdEOYrj
            PORT: 3000
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Cache Dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies
              run: npm ci
            - name: Run Server
              run: npm start & npx wait-on http://localhost:${{ env.PORT }}
            - name: Test code
              run: npm run test
            - name: Output Infmartion
              run: |
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Output Information
              run: |
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
                echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"