name: First Workflow

on:
    workflow_dispatch:

jobs:
    hello_world_job:
        runs-on: macos-latest

        steps:
            - name: Print Hello World
              run: echo "Hello, World!"