name: First Workflow

on:
    workflow_dispatch:

jobs:
    hello_world_job:
        runs-on: macos-latest

        steps:
            - name: Print Hello World
              run: echo "Hello, World!"
            - name: Print Goodbye World
              run: echo "Goodbye, World!"
            - name: Multiple Line Commnad
              run: |
                echo "This is the first line"
                echo "This is the second line"
                echo "This is the third line"