name: Output some Information
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: GitHub Context
              run: echo "${{ toJSON(github) }}"
              