name: Test, Lint, and Build
on: [push, workflow_dispatch]

jobs:
  lint-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
  test-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  build-code:
    runs-on: ubuntu-20.04
    needs: test-code
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist
  deploy-code:
    runs-on: ubuntu-20.04
    needs: build-code
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: Show artifacts
        run: tree
      - name: Deploy to production
        run: echo "Deploying to production"