name: Test, Lint, and Build
on: push, workflow_dispatch

jobs:
  lint-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Lint the code
        run: npm run lint
  test-code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy-code:
    runs-on: ubuntu-20.04
    needs: test-code
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy to production
        run: echo "Deploying to production"