name: Dump Secret to File

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
    DOCKER_TAG_NAME: latest

jobs:
  dump-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Secret to File
        shell: pwsh
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # Define the output file path
          # $outputFile = "./secret_output.txt"
          # Dump the secret content into the file
          Set-Content -Path .env.${{ env.DOCKER_TAG_NAME }} -Value "$env:MY_SECRET"
          Write-Host "env.${{ env.DOCKER_TAG_NAME }}"
          $variable = Get-Content -Path .env.${{ env.DOCKER_TAG_NAME }}
          Write-Host $variable
          Get-Location
          Get-ChildItem

      - name: Multiline Command
        run: |
            Write-Host "This is a multiline command 1"
            Write-Host "This is a multiline command 2"
            Write-Host "This is a multiline command 3"
            Write-Host "This is a multiline command 4"
        shell: pwsh 
      - name: Upload File to Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .env.${{ env.DOCKER_TAG_NAME }}