name: Dump Secret to File

on:
  workflow_dispatch:   
  push:
    branches:
      - main

jobs:
  dump-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dump Secret to File
        shell: pwsh
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          $outputFile = "./secret_output.txt"
          Set-Content -Path secret_output.txt -Value $env:MY_SECRET
          Set-Content -Path secret.txt -Value "Salida de secret.txt"
          Get-Content -Path $outputFile
          
      - name: Display created file
        run: |
            cat ./secret_output.txt
            cat ./secret.txt
            more ./secret_output.txt            