name: Dump Secret to File

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
    DOCKER_TAG_NAME: latest

jobs:
  dump-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Secret to File
        shell: pwsh
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # Define the output file path
          # $outputFile = "./secret_output.txt"
          New-Item -Path .envs/ -ItemType Directory; Set-Location -Path .envs/
          Get-Location
          Get-ChildItem -Path .envs/
          
          # Dump the secret content into the file
          Set-Content -Path .env.${{ env.DOCKER_TAG_NAME }} -Value $env:MY_SECRET
          
          # Verify the file content (optional)
          Get-Content -Path .env.${{ env.DOCKER_TAG_NAME }}
      - name: Upload File to Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .envs/