name: Dump Secret to File

on:
  push:
    branches:
      - main

jobs:
  dump-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dump Secret to File
        shell: pwsh
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # Define the output file path
          $outputFile = "./secret_output.txt"
          
          # Write the secret content into the file without printing it
          Add-Content -Path $outputFile -Value $env:MY_SECRET

      - name: Confirm File Creation
        shell: bash
        run: |
          cat secret_output.txt
          
      - name: Display File Content
        shell: bash
        run: |
          echo "$env:MY_SECRET" >> secret_output.txt
          cat secret_output.txt