name: Run Unit Tests
on: [push, pull_request]

jobs:
    test-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy-code:
        needs: test-code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: npm ci
            - name: Build code
              run: npm run build
            - name: Deploy to production
              run: echo "Deploying to production"